// src/example/App.tsx
import type { Component } from "solid-js";
import RadicalSelector from "./RadicalSelector";

const App: Component = (_props) => {
  return (
    <>
      <div class="App__selector">
        <RadicalSelector></RadicalSelector>
      </div>
      
      <style jsx>{`

.App__selector {
  width: 40rem;
  justify-self: center;
  background-color: var(--gray-100);
  margin: 2rem;
  padding: 1rem;
  border-radius: 0.25rem;
}

    `}</style>
    </>
  );
};

export default App;

// src/example/App.svelte
<script lang="ts">
	import RadicalsSelector from "./RadicalsSelector.svelte";
</script>

<main class="root">
	<RadicalsSelector />
</main>

<style lang="scss">
.root {
	justify-self: center;
	margin: 2rem;
	background-color: var(--snow-storm-1);
	border-radius: 0.25rem;
	border-color: var(--snow-storm-2);
	border-style: solid;
	border-width: 2px;
}
</style>
