// src/example/RadicalGroup.svelte
<script lang="ts">
  import type { RadicalGroup } from "./radical_group";

  export let group: RadicalGroup;
</script>

<ul class="root">
  <li class="strokes">
    <span class="hidden">Radicals with</span>
    {group.strokes}
    <span class="hidden">strokes</span>
  </li>
  {#each group.radicals as radical}
    <li class="radical">
      <input
        class="hidden"
        type="checkbox"
        name="radical-selector"
        id={radical.id}
        value={radical.literal}
        bind:checked={radical.checked}
      />
      <label class="radical-checkbox noto" for={radical.id}>
        {radical.literal}
      </label>
    </li>
  {/each}
</ul>

<style lang="scss">
  .root {
    user-select: none;
  }

  .root,
  .radical {
    display: contents;
  }

  .radical-checkbox,
  .strokes {
    justify-items: center;
    align-items: center;
  }

  .strokes {
    font-weight: 700;
    cursor: none;
    border-style: solid;
    border-radius: 0.25rem;
    border-width: 1px;
    border-color: var(--gray-400);
    width: 1.5rem;
    height: 1.5rem;
    justify-self: center;
    align-self: center;
  }

  .radical-checkbox {
    cursor: pointer;
    border-radius: 0.25rem;

    &:hover {
      background-color: var(--snow-storm-2);
    }

    &:active {
      background-color: var(--gray-300);
    }
  }

  input:checked + .radical-checkbox {
    background-color: var(--gray-300);
  }
</style>

// src/example/RadicalGroup.tsx
import { Component, For } from "solid-js"
import { RadicalAll } from "../lib/radical_all_access"

interface Props {
	radical: RadicalAll
}

export const RadicalGroup: Component<Props> = (props) => {
	return (
		<>
			<div class="RadicalGroup">
				<div class="RadicalGroup__strokes">
					{props.radical.strokes}
				</div>
				<ul class="RadicalGroup__list">
					<For each={props.radical.literals}>{(literal, _i) => (
						<li>
							<button class="RadicalGroup__button">
								{literal}
							</button>
						</li>
					)}</For>
				</ul>
			</div>

			<style jsx>{`

.RadicalGroup {
	grid-template-columns: 2rem 1fr;
}

.RadicalGroup__list {
	grid-template-columns: repeat(auto-fill, 2rem);
	grid-auto-rows: 2rem;
	padding: 0.5rem;
}

.RadicalGroup__strokes {
	align-items: center;
	justify-items: center;
	border-right-style: solid;
	border-right-width: 1px;
	border-right-color: var(--gray-300);
	font-weight: 700;
}

.RadicalGroup__button {
	align-items: center;
	justify-items: center;
	border-radius: 0.25rem;

	&:hover {
			background-color: var(--gray-300);
	}
	
	&:active {
			background-color: var(--gray-400);
	}
}

		`}</style>
		</>
	)
}
